book/urls.py
from django.urls import path
# from .views import list_books,delete_book,edit_book,
from .views import (
    list_publication,
    create_publication,
    update_publication,
    delete_publication
    
)
from .views import (
    list_genre,
    create_genre,
    update_genre,
    delete_genre
)
from .views import (
    list_book,
    create_book,
    read_book,
    update_book,
    delete_book
)
 



urlpatterns = [
    path('list/',list_book,name='list_book'),
    path('create/',create_book,name='create_book'),
    path('read/<id>',read_book,name='read_book'),
    path('update/<id>',update_book,name='update_book'),
    path('delete/<id>',delete_book,name='delete_book'),
    path("publication/list",list_publication ,name='list_publication'),
    path("publication/create",create_publication,name='create_publication'),
    path("publication/update/<id>",update_publication,name='update_publication'),
    path('publication/delete/<id>/', delete_publication, name='delete_publication'),
    path('genre/list/',list_genre,name='list_genre'),
    path('genre/create/',create_genre,name='create_genre'),
    path('genre/update/<id>',update_genre,name='update_genre'),
    path('genre/delete/<id>',delete_genre,name='delete_genre'),
    
    
    
    
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('', include('home.urls')),  
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),  
    path('book/', include('book.urls')),  
    path('author/',include('author.urls'))
   
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from author.models import Author

# Create your models here.
class Publication(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    phone = models.PositiveBigIntegerField()
    email = models.EmailField()
    website = models.URLField()
    is_active = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name
    


class Genre(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    is_active = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    file = models.FileField(upload_to='book/',blank=True, null=True)
    image = models.ImageField(upload_to='book/images',null=True,blank=True)
    publication = models.ForeignKey(Publication, on_delete=models.RESTRICT)
    genre = models.ManyToManyField(Genre)
    author = models.ManyToManyField(Author)
    edition = models.PositiveIntegerField()
    rating = models.DecimalField(max_digits=5, decimal_places=2)
    ISBN_number = models.CharField(null=True, blank=True,max_length=40)
    page_number = models.IntegerField()
    description = models.CharField(max_length=255, null=True,blank=True)
    demo_text = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    discount_percent = models.DecimalField(max_digits=9, decimal_places=2)
    volume = models.IntegerField()
    language = models.CharField(max_length=10, null=True, blank=True)
    is_active = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

book/forms.py
from django import forms
from book.models import Publication,Genre,Book



class PublicationForm(forms.ModelForm):
    class Meta:
        model=Publication
        fields='__all__'

class GenreForm(forms.ModelForm):
    class Meta:
        model=Genre
        fields='__all__'
        
        
class BookForm(forms.ModelForm):
    class Meta:
        model=Book
        fields='__all__'

book/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from .models import Book, Genre, Publication
from .forms import BookForm, GenreForm, PublicationForm

@login_required
def list_publication(request):
    publications = Publication.objects.filter(is_active=True)
    context = {
        "publications": publications
    }
    return render(request, 'publication/index.html', context)

@login_required
def create_publication(request):
    if request.method == 'POST':
        form = PublicationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Publication added successfully.')  
            return redirect('list_publication') 
        else:
            messages.error(request, 'Error adding publication. Please check the form.')  
    else:
        form = PublicationForm()

    context = {'form': form}
    return render(request, 'publication/create.html', context)

@login_required
def update_publication(request, id):
    publication = get_object_or_404(Publication, id=id)
    form = PublicationForm(request.POST or None, instance=publication)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('list_publication')
        else:
            print(form.errors)
    
    context = {'form': form}
    return render(request, 'publication/update.html', context)

@login_required
def delete_publication(request, id):
    publication = get_object_or_404(Publication, id=id)
    publication.delete()
    return redirect('list_publication')

@login_required
def list_genre(request):
    genres = Genre.objects.all()
    active_genres = Genre.objects.filter(is_active=True)
    context = {
        'genres': genres,
        'active_genres': active_genres
    }
    return render(request, 'genre/index.html', context)

@login_required
def create_genre(request):
    if request.method == 'POST':
        form = GenreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list_genre')
        else:
            print(form.errors)
    else:
        form = GenreForm()

    context = {"form": form}
    return render(request, "genre/create.html", context)

@login_required
def update_genre(request, id):
    genre = get_object_or_404(Genre, id=id)
    form = GenreForm(request.POST or None, instance=genre)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('list_genre')
        else:
            print(form.errors)

    context = {
        "genre": genre,
        "form": form
    }
    return render(request, 'genre/update.html', context)

@login_required
def delete_genre(request, id):
    genre = get_object_or_404(Genre, id=id)
    genre.delete()
    return redirect('list_genre')

def create_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('list_book')
    else:
        form = BookForm()
    
    context = {'form': form}
    return render(request, 'book/create.html', context)

def read_book(request, id):
    book = get_object_or_404(Book, id=id)
    context = {
        'book': book  
    }
    return render(request, 'book/read.html', context)


def update_book(request, id):
    book = get_object_or_404(Book, id=id)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect('list_book')
    
    form = BookForm(instance=book)

    context = {
        'form': form,
        'book': book  
    }
    return render(request, 'book/update.html', context)

def delete_book(request, id):
    book = get_object_or_404(Book, id=id)
    book.delete()
    return redirect('list_book')

def list_book(request):
    books = Book.objects.filter(is_active=True).order_by('-name')
    context = {'books': books}
    return render(request, 'book/index.html', context)

book/templates/book/create.html
{% extends "home/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">Add Book</h4>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="id_name">Name</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="id_image">Image</label>
                        {{ form.image }}
                    </div>
                    <div class="form-group">
                        <label for="id_file">File</label>
                        {{ form.file }}
                    </div>
                    <div class="form-group">
                        <label for="id_publication">Publication</label>
                        {{ form.publication }}
                    </div>
                    <div class="form-group">
                        <label for="id_genre">Genre:</label>
                        {{ form.genre }}
                    </div>
                    <div class="form-group">
                        <label for="id_author">Author:</label>
                        {{ form.author }}
                    </div>
                    <div class="form-group">
                        <label for="id_edition">Edition</label>
                        {{ form.edition }}
                    </div>
                    <div class="form-group">
                        <label for="id_rating">Rating</label>
                        {{ form.rating }}
                    </div>
                    <div class="form-group">
                        <label for="id_ISBN_number">ISBN Number</label>
                        {{ form.ISBN_number }}
                    </div>
                    <div class="form-group">
                        <label for="id_page_number">Page Number</label>
                        {{ form.page_number }}
                    </div>
                    <div class="form-group">
                        <label for="id_description">Description</label>
                        {{ form.description }}
                    </div>
                    <div class="form-group">
                        <label for="id_demo_text">Demo Text</label>
                        {{ form.demo_text }}
                    </div>
                    <div class="form-group">
                        <label for="id_price">Price</label>
                        {{ form.price }}
                    </div>
                    <div class="form-group">
                        <label for="id_discount_percent">Discount Percent</label>
                        {{ form.discount_percent }}
                    </div>
                    <div class="form-group">
                        <label for="id_volume">Volume</label>
                        {{ form.volume }}
                    </div>
                    <div class="form-group">
                        <label for="id_language">Language</label>
                        {{ form.language }}
                    </div>
                    <div class="form-group">
                        <label for="id_is_active">Is Active</label>
                        {{ form.is_active }}
                    </div>
                    
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

book/templates/book/index.html
{% extends "home/base.html" %}
{% block content %}
				
    <!-- Page Header -->
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Book</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Book</li>
                </ul>
            </div>
            <div class="col-auto float-right ml-auto">
                <a href="{% url 'create_book' %}" class="btn add-btn"><i class="fa fa-plus"></i> Add Book</a>
                
            </div>
        </div>
    </div>
    
    <div class="row staff-grid-row">
        {% for book in books %}
        <div class="col-md-4 col-sm-6 col-12 col-lg-4 col-xl-3">
            <div class="profile-widget">
                <div class="profile-img">
                    <img alt="" src="{{book.image.url}}" class="avatar">
                </div>
                <h4 class="user-name m-t-10 mb-0 text-ellipsis">{{book.name}}</h4>
                <h5 class="user-name m-t-10 mb-0 text-ellipsis">{% for author in book.author.all %}
                                                                {{ author.name }}                                                       
                                                                {% endfor %}</h5>

                <div class="small text-muted">Rs {{book.price}}</div>
                <a href="{% url 'read_book' book.id %}" class="btn btn-white btn-sm m-t-10">View</a>
                <a href="{% url 'update_book' book.id %}" class="btn btn-white btn-sm m-t-10">Edit</a>
                <a href="{% url 'delete_book' book.id %}" class="btn btn-white btn-sm m-t-10">Delete</a>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock content %}

book/templates/book/read.html
{% extends "home/base.html" %}

{% block content %}
    <!-- Page Content -->
    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <h3 class="page-title">{{ book.name }}</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active">{{ book.name }}</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /Page Header -->

    <div class="card mb-0">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="profile-view">
                        <a href="#">
                            {% load static %}
                            <img src="{{ book.image.url }}" alt="Book Image" style="width: 200px; height: auto;">
                        </a>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="profile-basic">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="profile-info-left">
                                    <h3 class="user-name m-t-0">
                                        {% for author in book.author.all %}
                                            {{ author.name }}
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </h3>
                                    <h5 class="company-role m-t-0 mb-0">
                                        {% for genre in book.genre.all %}
                                            {{ genre.name }}
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </h5>
                                    <div class="staff-id">ISBN: {{ book.isbn }}</div>
                                    <div class="staff-msg">
                                        <a href="#" class="btn btn-primary" style="color: white;">Rs {{ book.price }}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <ul class="personal-info">
                                    <li>
                                        <span class="title">Edition:</span>
                                        <span class="text">{{ book.edition }}</span>
                                    </li>
                                    <li>
                                        <span class="title">Volume:</span>
                                        <span class="text">{{ book.volume }}</span>
                                    </li>
                                    <li>
                                        <span class="title">Language:</span>
                                        <span class="text">{{ book.language }}</span>
                                    </li>
                                    <br>
                                    <hr>
                                    
                                        
                                        <p>{{ book.description }}</p>
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

book/templates/book/update.html
{% extends "home/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">Book Edit  Form</h4>
            </div>
            <div class="card-body">
                <form method = 'POST' enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        {{ form.as_p}}
                    </div>
                    
                    
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

    {% endblock content %}